### ISSUE TITLE
Question: How is this used with DataDog?

### ISSUE THREAD

**Issue by buzzedword** [remind101/ecsdog#1]
You seem to be making an assumption regarding DataDog and the end user's infrastructure-- I'm attempting to follow it here.
1. The datadog agent is running on the Docker host machine for ecsdog
2. `-statsd` environment is the DogStatsD ingress

Is this correct?

**Comment by ejholmes** [comment]
@buzzedword it just requires that you have a [dogstatsd daemon](https://github.com/DataDog/dd-agent) running somewhere (usually on the localhost), and you can use the `-statsd` flag to define that.

**Comment by buzzedword** [comment]
Fantastic. I see how this can be used within ECS now. All roads will eventually lead to Empire, might as well get this integrated now :)

Thank you!
